layout:
  qmk_keyboard: splitkb/aurora/sofle_v2/rev1
layers:
  BASE:
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - [null, Q, W, E, R, T, Y, U, I, O, P, null]
    - [null, {h: Gui, t: A}, {h: Alt, t: S}, {h: Ctrl, t: D}, {h: Shift, t: F}, {h: Esc, t: G}, {h: Tab, t: H}, {h: Shift, t: J}, {h: Ctrl, t: K}, {h: Alt, t: L}, {h: Gui, t: ";", s: ":"}, null]
    - [null, Z, X, C, V, {h: "$$material:block$$", t: B}, "$$material:volume_off$$", "$$material:volume_off$$", N, M, {t: ",", s: "<"}, {t: ".", s: ">"}, {t: "/", s: "?"}, null]
    - null
    - null
    - {h: "$$material:content_paste$$", t: "$$material:content_copy$$", s: "$$material:content_cut$$"}
    - {h: "$$material:assistant_navigation$$", t: "$$material:backspace$$"}
    - {h: "$$material:function$$", t: "$$material:keyboard_return$$"}
    - {h: "$$material:sports_esports$$", t: "$$material:space_bar$$"}
    - {h: "$$material:mouse$$", t: "$$material:pin$$"}
    - "$$material:keyboard_capslock_badge$$"
    - null
    - null

  NUM:
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - [null, {t: Q, type: trans}, {t: W, type: trans}, {t: "$$mdi:minus-thick$$", s: "$$material:border_color$$"}, {t: R, type: trans}, {t: T, type: trans}, {t: Y, type: trans}, {t: "\\", s: "|"}, {t: "=", s: "+"}, {t: O, type: trans}, {t: P, type: trans}, null]
    - [null, {h: Gui, t: 5, s: "%"}, {h: Alt, t: 4, s: "$"}, {h: Ctrl, t: 3, s: "#"}, {h: Shift, t: 2, s: "@"}, {h: Esc, t: 1, s: "!"}, {h: Tab, t: 6, s: "^"}, {h: Shift, t: 7, s: "&"}, {h: Ctrl, t: 8, s: "*"}, {h: Alt, t: 9, s: "("}, {h: Gui, t: 0, s: ")"}, null]
    - [null, {t: Z, type: trans}, {t: ";", s: ":"}, {t: "[", s: "{"}, {t: "`", s: "~"}, "$$material:block$$", {t: "$$material:volume_off$$", type: trans}, {t: "$$material:volume_off$$", type: trans}, {t: N, type: trans}, {t: "/", s: "?"}, {t: "]", s: "}"}, {t: "'", s: "$$mdi:format-quote-close$$"}, {t: "/", s: "?", type: trans}, null]
    - null
    - null
    - {h: "$$material:content_paste$$", t: "$$material:content_copy$$", s: "$$material:content_cut$$", type: trans}
    - {h: "$$material:assistant_navigation$$", t: "$$material:backspace$$", type: trans}
    - {h: "$$material:function$$", t: "$$material:keyboard_return$$", type: trans}
    - {h: "$$material:sports_esports$$", t: "$$material:space_bar$$", type: trans}
    - {h: "$$material:mouse$$", t: "$$material:pin$$", type: trans}
    - {t: "$$material:keyboard_capslock_badge$$", type: trans}
    - null
    - null

  FNG:
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - [F13, F14, F15, F16, F17, F18, F19, F20 , F21, F22, F23, F24]
    - [F1, {h: Gui, t: F2}, {h: Alt, t: F3}, {h: Ctrl, t: F4}, {h: Shift, t: F5}, {h: Esc, t: F6}, {h: Tab, t: F7}, {h: Shift, t: F8}, {h: Ctrl, t: F9}, {h: Alt, t: F10}, {h: Gui, t: F11}, F12]
    - [null, Ä, ẞ, €, {t: "V", type: trans}, "$$material:block$$", {t: "$$material:volume_off$$", type: trans}, {t: "$$material:volume_off$$", type: trans}, {t: N, type: trans}, Ü, {t: ",", s: "<", type: trans}, Ö, {t: "/", s: "?", type: trans}, null]
    - null
    - null
    - {h: "$$material:content_paste$$", t: "$$material:content_copy$$", s: "$$material:content_cut$$", type: trans}
    - {h: "$$material:assistant_navigation$$", t: "$$material:backspace$$", type: trans}
    - {h: "$$material:function$$", t: "$$material:keyboard_return$$", type: trans}
    - {h: "$$material:sports_esports$$", t: "$$material:space_bar$$", type: trans}
    - {h: "$$material:mouse$$", t: "$$material:pin$$", type: trans}
    - {t: "$$material:keyboard_capslock_badge$$", type: trans}
    - null
    - null

  NAV:
    - [null, null, null, null, null, null, null, null, null, null, null, null]
    - [null, {t: Q, type: trans}, {t: W, type: trans}, {t: "$$material:keyboard_tab_rtl$$"},  {t: "$$material:select_window_2$$"}, {t: T, type: trans}, {t: "$$material:expand_circle_up$$"}, {h: "$$material:text_select_move_forward_word$$", t: "$$mdi:backspace-outline$$"} , {h: "$$material:text_select_move_up$$", t: "$$material:keyboard_arrow_up$$"}, {h: "$$material:text_select_move_back_word$$", t: "$$mdi:backspace-reverse-outline$$"}, {t: "$$material:screenshot_monitor$$"}, null]
    - [null, {t: Gui}, {t: Alt}, {t: Ctrl}, {t: Shift}, {t: Esc}, {t: Tab}, {h: "$$material:text_select_jump_to_beginning$$", t: "$$material:keyboard_arrow_left$$"}, {h: "$$material:text_select_move_down$$", t: "$$material:keyboard_arrow_down$$"}, {h: "$$material:text_select_jump_to_end$$", t: "$$material:keyboard_arrow_right$$"}, {h: Gui, t: ";", s: ":", type: trans}, null]
    - [null, {t: "z", type: trans}, {t: "x", type: trans}, "$$material:left_panel_close$$", "$$material:right_panel_close$$", "$$material:block$$", {t: "$$material:volume_off$$", type: trans}, {t: "$$material:volume_off$$", type: trans}, {t: "$$material:expand_circle_down$$"}, {t: M, type: trans}, {t: ",", s: "<", type: trans}, {t: ".", s: ">", type: trans}, {t: Ins}, null]
    - null
    - null
    - {h: "$$material:content_paste$$", t: "$$material:content_copy$$", s: "$$material:content_cut$$", type: trans}
    - {h: "$$material:assistant_navigation$$", t: "$$material:backspace$$", type: trans}
    - {h: "$$material:function$$", t: "$$material:keyboard_return$$", type: trans}
    - {h: "$$material:sports_esports$$", t: "$$material:space_bar$$", type: trans}
    - {h: "$$material:mouse$$", t: "$$material:pin$$", type: trans}
    - {t: "$$material:keyboard_capslock_badge$$", type: trans}
    - null
    - null