manifest:
  remotes:
    - name: saitama
      url-base: https://github.com/saitamandl
  projects:
    - name: zmk
      remote: saitama
      revision: exp/feats
      import: app/west.yml
  self:
    path: config
